### ISSUE TITLE
In lining CSS breaks styles.

### ISSUE THREAD

**Issue by JojokCreator** [astro-community/AstroCritters#295]
Hi, trying to use this amazing tool in a project. It works well for the most part but I have a few pages with embedded videos using https://astro-embed.netlify.app/components/youtube/ when I build and deploy the project the styles on the videos seem to get broken.

https://stackblitz.com/edit/withastro-astro-wsnvzt <-- example here. 

To reproduce run `npm run dev` = styles are okay.

`npm run preview` (with the inlined css) = styles are broken.

**Comment by ebursztein** [comment]
Thanks

**Comment by NikolaRHristov** [comment]
@JojokCreator I tried running it with:

```sh
npm install ; npm run build ; npm run preview
```

and styles are working correctly and they're inlined:

![image](https://github.com/user-attachments/assets/adc422e5-8206-4722-bc04-9690b9a878be)

Am I missing something?

**Comment by JojokCreator** [comment]
Hi, Thanks for looking into this. Open the page in a new tab and press play on the video.

![image](https://github.com/user-attachments/assets/fe7648b3-57c8-42bc-8454-4593f0fc9c4e)

It doesn't fill the container like it should,  normally.

**Comment by NikolaRHristov** [comment]
Managed to reproduce. I think this is due to `reduceInlineStyles` https://github.com/GoogleChromeLabs/critters#properties

```
reduceInlineStyles [Boolean]

(https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Boolean) 
Option indicates if inline styles should be evaluated for critical CSS.

By default inline style tags will be evaluated and rewritten to only contain critical CSS.

Set it to false to skip processing inline styles. (default: true)
```

```ts
import { defineConfig } from 'astro/config';

// https://astro.build/config
export default defineConfig({
  integrations: [
    (await import('@playform/inline')).default({
      Critters: {
        reduceInlineStyles: false,
      },
    }),
  ],
});
```

should be working fine:

![image](https://github.com/user-attachments/assets/a16ccbbb-a328-4fd3-8279-af3e65f4f74d)

Somehow these styles get omitted because there's no active class on the component yet.

![image](https://github.com/user-attachments/assets/531182ab-f0a2-4ff7-a0ce-564bbbe12560)

`reduceInlineStyles`

Will be disabled by default in the latest version.

**Comment by JojokCreator** [comment]
Perfect thank you.

________________________________
